export const PUT_FETCHED_DATA = 'PUT_FETCHED_DATA'
export const FILTER_SRC_STATE_SWAP = 'FILTER_SRC_STATE_SWAP'
export const ADD_NEW_FILTER_LABEL = 'ADD_NEW_FILTER_LABEL'
export const REMOVE_FILTER_LABEL = 'REMOVE_FILTER_LABEL'
export const IS_FILTER_MENU = 'IS_FILTER_MENU'
export const SET_EXP_LEVEL = 'SET_EXP_LEVEL'
export const GET_LOCAL_STATE = 'GET_LOCAL_STATE'
export const SET_PARSED_DATA = 'SET_PARSED_DATA'

